# Generated by Django 3.2.5 on 2021-07-26 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2021, 7, 26, 16, 45, 29, 206053)),
        ),
    ]
